//
//  ViewPresenter.swift
//  SampleCompletionHandlerSafer
//
//  Created by Papon Supamongkonchai on 1/3/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewPresentationLogic
{
    func presentImagesPicsum(response: View.FetchImageURL.Response)
    func presentSetStartText()
    func presentFeedNews(response: View.NewsFeed.Response)
}

class ViewPresenter: ViewPresentationLogic
{
    weak var viewController: ViewDisplayLogic?
    
    // MARK: Present request
    
    func presentImagesPicsum(response: View.FetchImageURL.Response)
    {
        let viewModel = View.FetchImageURL.ViewModel(startIndex: response.startIndex, 
                                                     endIndex: response.endIndex,
                                                     urls: response.urls)
        viewController?.displayImagesPicsum(viewModel: viewModel)
    }
    
    func presentFeedNews(response: View.NewsFeed.Response)
    {
        let viewModel = View.NewsFeed.ViewModel(articles: response.news?.articles)
        viewController?.displayFeedNews(viewModel: viewModel)
    }
    
    // MARK: Do something
    
    func presentSetStartText()
    {
        let viewModel = View.DisplayModel(isHide: true)
        viewController?.displaySetStartText(viewModel: viewModel)
    }
}
