//
//  ViewWorker.swift
//  SampleCompletionHandlerSafer
//
//  Created by Papon Supamongkonchai on 1/3/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewWorkerInterface {
    func generateListURL(startIndex: Int, endIndex: Int, success:([String]) -> Void)
}

class ViewWorker
{
    func generateListURL(startIndex: Int, endIndex: Int, success:([String]) -> Void) {
        let listImageURL = (startIndex...endIndex).map {
            getURLSpecificImageLoad(id: $0)
        }
        success(listImageURL)
    }
}

extension ViewWorker {
    //MARK: path URL Image From PICSUM
    func getURLSpecificImageLoad(
        id: Int ,
        widthImg: Int = 200,
        heightImg: Int = 300
    ) -> String {
        let idPath = "/id/\(id)"
        let widthHeightPath = "/\(widthImg)/\(heightImg)"
        return "https://picsum.photos\(idPath)\(widthHeightPath)"
    }
}
